In [8]:
import pandas as pd

csv_file_path = r"C:\Users\FORMACAO\Documents\this_is_the_repo\python-trainning\python\day_10\examples\simple_pandas\inputs\employees.csv"


# Read the CSV file into a DataFrame
df = pd.read_csv(csv_file_path)

def filter_data(df: pd.DataFrame) -> pd.Series:
    """
    Filter the given DataFrame based on the condition that the "Salary" column is greater than 50000.

    Parameters:
        df (pandas.DataFrame): The input DataFrame to be filtered.

    Returns:
        pandas.Series: The filtered DataFrame.
    """
    df_slice = df[df["Salary"] > 50000]
    new_df = (
        df_slice.copy()
    ) 
    return new_df

filtered_df = filter_data(df)

print(filtered_df.head(5))


def select_columns(df: pd.DataFrame) -> pd.Series:
    """
    Selects specific ["Name", "Age", "Salary", "Country"] columns from a DataFrame.

    Parameters:
        df (pd.DataFrame): The input DataFrame.

    Returns:
        pd.Series: A new DataFrame containing only the selected columns.
    """
    df_slice = df[["Name", "Age", "Salary", "Country"]]
    new_df = df_slice.copy()

    return new_df

selected_df = select_columns(df)

print(selected_df.head(5))

def calculate_bonus(salary: float) -> float:
    """
    Calculate the bonus based on the given salary.

    Parameters:
    salary (float): The salary of the employee.

    Returns:
    float: The calculated bonus.
    """
    return salary * 0.1

selected_df['Bonus'] = selected_df['Salary'].apply(calculate_bonus)

print(selected_df.head(5))

def get_country_name(country_code: str) -> str:
    """
    Returns the name of a country based on its country code.

    Args:
        country_code (str): The country code.

    Returns:
        str: The name of the country corresponding to the country code. If the country code is not found, 'Unknown' is returned.
    """
    countries = {
        'USA': 'United States',
        'France': 'France'
    
    }
    return countries.get(country_code, 'Unknown')

selected_df['Country'] = selected_df['Country'].apply(get_country_name)

print(selected_df.head(5))

     Name  Age  Gender Department  Salary              Email       Phone  \
0   GMKEU   55    Male  Marketing   70467  gmkeu@company.com   996823412
4   ENLRK   52    Male    Finance   52023  enlrk@company.com  8468707446
5   VQQRP   22  Female         IT   61055  vqqrp@company.com  4223727997
6   DAULT   56  Female  Marketing   51351  dault@company.com  5189821734
12  CYZPY   48  Female    Finance   79100  cyzpy@company.com  1476262966

       Address      City State Country  Postal Code
0   WXEYPH2J6H  New York    TX     USA        69962
4   SD7GTTO62M     Paris    CA     USA        78487
5   504C87EVGB     Paris    FL  France        64816
6   74QJZKLYDH    London    TX     USA        63412
12  LYBDTBJUMI     Tokyo    FL     USA        75292
    Name  Age  Salary Country
0  GMKEU   55   70467     USA
1  JNTVL   59   42577  France
2  LXJJN   32   44144      UK
3  AAOJG   27   43716   Japan
4  ENLRK   52   52023     USA
    Name  Age  Salary Country   Bonus
0  GMKEU   55   70467     USA  7046.7
1  JNTVL   59   42577  France  4257.7
2  LXJJN   32   44144      UK  4414.4
3  AAOJG   27   43716   Japan  4371.6
4  ENLRK   52   52023     USA  5202.3
    Name  Age  Salary        Country   Bonus
0  GMKEU   55   70467  United States  7046.7
1  JNTVL   59   42577         France  4257.7
2  LXJJN   32   44144        Unknown  4414.4
3  AAOJG   27   43716        Unknown  4371.6
4  ENLRK   52   52023  United States  5202.3

In [9]:
selected_df['Country'] = selected_df['Country'].map({
    'USA': 'United States',
    'France': 'France'
})
selected_df.to_csv('new_output_pandas.csv', index=True)